CREATE TABLE IF NOT EXISTS PROFIL(
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PSEUDO VARCHAR(16),
    EMAIL VARCHAR(50) UNIQUE,
    DESCRIPTION TEXT,
    PROFIL_PICTURE VARCHAR(25),
    PASSWORD TEXT,
    CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE IF EXISTS PROFIL
ADD COLUMN IF NOT EXISTS DESCRIPTION TEXT,
ADD COLUMN IF NOT EXISTS PROFIL_PICTURE VARCHAR(25);

CREATE TABLE IF NOT EXISTS LIST(
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME TEXT,
    MEDIA_TYPE MEDIA,
    PROFIL_ID INTEGER,
    CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(PROFIL_ID) REFERENCES PROFIL(ID)
);

CREATE TABLE IF NOT EXISTS LIST_MEDIA_ITEM(
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    EXTERNAL_ID INTEGER,
    LIST_ID INTEGER,
    FOREIGN KEY(LIST_ID) REFERENCES LIST(ID)
);

CREATE TABLE IF NOT EXISTS REVIEW(
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    COMMENT TEXT,
    RATE NUMERIC,
    MEDIA_TYPE MEDIA,
    EXTERNAL_ID INTEGER,
    PROFIL_ID INTEGER,
    CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(PROFIL_ID) REFERENCES PROFIL(ID)
);

CREATE TABLE IF NOT EXISTS PROFIL_MEDIA_STATUS(
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    EXTERNAL_ID INTEGER,
    MEDIA_TYPE MEDIA,
    STATUS STATUS,
    PROFIL_ID INTEGER,
    CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(PROFIL_ID) REFERENCES PROFIL(ID)
);
